import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import type { ActualResult, Match, MatchStatus } from "../src/types/prode";
import { outcomeFromGoals } from "../src/utils/outcome";
import { isParticipantCsvFile } from "./csvParticipants";

export const RESULT_CSV_HEADERS = [
  "match_id",
  "home_goals",
  "away_goals",
  "status",
  "updated_at"
] as const;

export interface ResultsCsvSyncResult {
  results: ActualResult[];
  files: string[];
  warnings: string[];
}

interface ResultCsvRow {
  match_id: string;
  home_goals: string;
  away_goals: string;
  status: string;
  updated_at: string;
}

const allowedStatuses = new Set<MatchStatus>(["scheduled", "live", "finished"]);

export function readResultsFromCsvDir(csvDir: string, matches: Match[]): ResultsCsvSyncResult {
  if (!existsSync(csvDir)) {
    return { results: [], files: [], warnings: [] };
  }

  const csvFiles = readdirSync(csvDir).filter(isParticipantCsvFile).sort((left, right) => left.localeCompare(right));
  const resultsByMatchId = new Map<string, ActualResult>();
  const warnings: string[] = [];

  csvFiles.forEach((fileName) => {
    const filePath = join(csvDir, fileName);
    const fileResults = resultsFromCsv(readFileSync(filePath, "utf8"), fileName, matches, warnings);
    fileResults.forEach((result) => {
      if (resultsByMatchId.has(result.matchId)) {
        throw new Error(`${fileName}: resultado duplicado para match_id ${result.matchId}.`);
      }
      resultsByMatchId.set(result.matchId, result);
    });
  });

  return { results: [...resultsByMatchId.values()], files: csvFiles, warnings };
}

export function resultsFromCsv(
  csvContent: string,
  fileName: string,
  matches: Match[],
  warnings: string[] = []
): ActualResult[] {
  const rows = parseResultsCsv(csvContent, fileName);
  const matchIds = new Set(matches.map((match) => match.id));

  return rows.map((row, index) => {
    const rowNumber = index + 2;
    const matchId = row.match_id.trim();
    if (!matchIds.has(matchId)) {
      throw new Error(`${fileName}:${rowNumber}: match_id inexistente "${matchId}".`);
    }

    const status = parseStatus(row.status, fileName, rowNumber);
    const homeGoals = parseGoals(row.home_goals, "home_goals", status, fileName, rowNumber);
    const awayGoals = parseGoals(row.away_goals, "away_goals", status, fileName, rowNumber);

    if (status === "finished" && (homeGoals === null || awayGoals === null)) {
      throw new Error(`${fileName}:${rowNumber}: finished requiere home_goals y away_goals.`);
    }

    if (status !== "finished" && (homeGoals !== null || awayGoals !== null)) {
      warnings.push(`${fileName}:${rowNumber}: goles informados con status ${status}; no suman hasta finished.`);
    }

    return {
      matchId,
      status,
      homeGoals,
      awayGoals,
      outcome: status === "finished" ? outcomeFromGoals(homeGoals, awayGoals) : null,
      updatedAt: row.updated_at.trim() || new Date().toISOString(),
      provider: "manual-real"
    };
  });
}

export function parseResultsCsv(csvContent: string, fileName = "results.csv"): ResultCsvRow[] {
  const records = parseCsvRecords(csvContent).filter((record) =>
    record.some((value) => value.trim().length > 0)
  );

  if (records.length === 0) {
    throw new Error(`${fileName}: CSV vacío.`);
  }

  const [headerRecord, ...dataRecords] = records;
  const expectedHeaders = [...RESULT_CSV_HEADERS];
  const headers = headerRecord.map((header) => header.trim());

  if (headers.length !== expectedHeaders.length || headers.some((header, index) => header !== expectedHeaders[index])) {
    throw new Error(`${fileName}: encabezado inválido. Esperado: ${expectedHeaders.join(",")}.`);
  }

  return dataRecords.map((record, index) => {
    const rowNumber = index + 2;
    if (record.length !== expectedHeaders.length) {
      throw new Error(`${fileName}:${rowNumber}: se esperaban ${expectedHeaders.length} columnas y hay ${record.length}.`);
    }

    return {
      match_id: record[0].trim(),
      home_goals: record[1].trim(),
      away_goals: record[2].trim(),
      status: record[3].trim(),
      updated_at: record[4].trim()
    };
  });
}

export function writeGeneratedResults(outputFile: string, results: ActualResult[], csvFiles: string[]): void {
  mkdirSync(dirname(outputFile), { recursive: true });
  const fileContent = `/* Auto-generated by npm run sync:results. Do not edit manually. */
import type { ActualResult } from "../types/prode";

export const generatedResults: ActualResult[] = ${JSON.stringify(results, null, 2)};

export const generatedResultCsvFiles: string[] = ${JSON.stringify(csvFiles, null, 2)};
`;

  writeFileSync(outputFile, fileContent, "utf8");
}

export function syncResultsFromCsv(options: {
  projectRoot: string;
  matches: Match[];
  csvDir?: string;
  outputFile?: string;
}): ResultsCsvSyncResult {
  const csvDir = options.csvDir ?? join(options.projectRoot, "data", "results_csv");
  const outputFile = options.outputFile ?? join(options.projectRoot, "src", "data", "generatedResults.ts");
  const result = readResultsFromCsvDir(csvDir, options.matches);
  writeGeneratedResults(outputFile, result.results, result.files);
  return result;
}

export function formatResultsSyncSummary(projectRoot: string, outputFile: string, result: ResultsCsvSyncResult): string {
  const relativeOutput = relative(projectRoot, outputFile);
  if (result.files.length === 0) {
    return `No se encontraron CSV reales de resultados. Generado ${relativeOutput} con lista vacía.`;
  }

  return `Generado ${relativeOutput} con ${result.results.length} resultado(s) desde ${result.files
    .map((file) => basename(file))
    .join(", ")}.`;
}

function parseStatus(value: string, fileName: string, rowNumber: number): MatchStatus {
  const status = value.trim().toLowerCase() as MatchStatus;
  if (allowedStatuses.has(status)) return status;
  throw new Error(`${fileName}:${rowNumber}: status inválido "${value}".`);
}

function parseGoals(
  value: string,
  fieldName: "home_goals" | "away_goals",
  status: MatchStatus,
  fileName: string,
  rowNumber: number
): number | null {
  const trimmedValue = value.trim();
  if (trimmedValue === "") return null;
  const parsed = Number(trimmedValue);
  if (!Number.isInteger(parsed) || parsed < 0) {
    throw new Error(`${fileName}:${rowNumber}: ${fieldName} inválido "${value}".`);
  }

  if (status === "scheduled") {
    return null;
  }

  return parsed;
}

function parseCsvRecords(csvContent: string): string[][] {
  const records: string[][] = [];
  let currentRecord: string[] = [];
  let currentField = "";
  let inQuotes = false;

  for (let index = 0; index < csvContent.length; index += 1) {
    const char = csvContent[index];
    const nextChar = csvContent[index + 1];

    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        currentField += '"';
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === "," && !inQuotes) {
      currentRecord.push(currentField);
      currentField = "";
      continue;
    }

    if ((char === "\n" || char === "\r") && !inQuotes) {
      if (char === "\r" && nextChar === "\n") index += 1;
      currentRecord.push(currentField);
      records.push(currentRecord);
      currentRecord = [];
      currentField = "";
      continue;
    }

    currentField += char;
  }

  if (inQuotes) {
    throw new Error("CSV inválido: comillas sin cerrar.");
  }

  if (currentField.length > 0 || currentRecord.length > 0) {
    currentRecord.push(currentField);
    records.push(currentRecord);
  }

  return records;
}
