/* Auto-generated by npm run sync:results. Do not edit manually. */
import type { ActualResult } from "../types/prode";

export const generatedResults: ActualResult[] = [];

export const generatedResultCsvFiles: string[] = [];
